// Generated by tool/sounds.py - edit that, not this.

/// The built-in sounds, `sound:<name>` in an announcement.
const Map<String, String> kSounds = {
  'doorbell': 'ding-dong',
  'chime': 'one bell',
  'notify': 'two soft notes, a plain notification',
  'pop': 'a click, for a button',
  'alert': 'three beeps',
  'warning': 'two falling tones, twice: a door left open, a leak',
  'alarm': 'a siren, three seconds: smoke, intrusion',
  'armed': 'three rising beeps',
  'disarmed': 'three falling beeps',
  'success': 'a rising arpeggio: something completed',
  'error': 'two low buzzes: something failed',
  'knock': 'three knocks on wood',
  'ring': 'a phone ringing',
  'timer': 'a kitchen timer',
  'laundry': 'a little tune: the washer is done',
  'door_open': 'a short slide up',
  'door_close': 'a short slide down',
  'battery': 'two quiet low beeps',
  'morning': 'a gentle rising phrase',
  'goodnight': 'a slow falling phrase, quiet',
};
